const CATEGORIAS = [
  "AGRO",
  "ELÉCTRICO",
  "ABRASIVOS",
  "TORNILLERÍA",
  "MOTORES",
  "PRODUCTOS ORNAMENTACIÓN",
  "PINTURA",
  "SEGURIDAD INDUSTRIAL",
  "PRODUCTOS DEL HOGAR",
  "HIERRO",
  "HERRAMIENTAS ELÉCTRICAS",
  "TUBERÍA Y ACCESORIOS DE P.V.C",
  "MATERIALES PARA CONSTRUCCIÓN",
  "MANGUERAS",
  "TANQUES",
  "HERRAMIENTAS MANUALES",
  "BAÑOS Y COCINAS",
  "QUÍMICOS",
  "PLÁSTICOS Y MALLAS"
];

const PRODUCTOS = [
  /* ---------- AGRO ---------- */
  { categoria: "AGRO", nombre: "Cerca eléctrica" },
  { categoria: "AGRO", nombre: "Fumigadoras" },
  { categoria: "AGRO", nombre: "Herramientas" },
  { categoria: "AGRO", nombre: "Máquina agrícola" },
  { categoria: "AGRO", nombre: "Grapas y puntillas" },
  { categoria: "AGRO", nombre: "Alambre de púas" },
  { categoria: "AGRO", nombre: "Herraduras" },

  /* ---------- ELÉCTRICO ---------- */
  { categoria: "ELÉCTRICO", nombre: "Cable" },
  { categoria: "ELÉCTRICO", nombre: "Alambre" },
  { categoria: "ELÉCTRICO", nombre: "Lámparas" },
  { categoria: "ELÉCTRICO", nombre: "Bombillas" },
  { categoria: "ELÉCTRICO", nombre: "Accesorios eléctricos" },
  { categoria: "ELÉCTRICO", nombre: "Medidor" },
  { categoria: "ELÉCTRICO", nombre: "Cajas" },

  /* ---------- ABRASIVOS ---------- */
  { categoria: "ABRASIVOS", nombre: "Lijas" },
  { categoria: "ABRASIVOS", nombre: "Discos" },
  { categoria: "ABRASIVOS", nombre: "Grapas" },
  { categoria: "ABRASIVOS", nombre: "Limas" },
  { categoria: "ABRASIVOS", nombre: "Piedras" },

  /* ---------- TORNILLERÍA ---------- */
  { categoria: "TORNILLERÍA", nombre: "Drywall" },
  { categoria: "TORNILLERÍA", nombre: "Estufa" },
  { categoria: "TORNILLERÍA", nombre: "Carriage" },
  { categoria: "TORNILLERÍA", nombre: "Tuercas" },
  { categoria: "TORNILLERÍA", nombre: "ROG" },
  { categoria: "TORNILLERÍA", nombre: "Lámina" },
  { categoria: "TORNILLERÍA", nombre: "Autoperforante" },
  { categoria: "TORNILLERÍA", nombre: "Cabeza de lenteja" },
  { categoria: "TORNILLERÍA", nombre: "Grado 6" },
  { categoria: "TORNILLERÍA", nombre: "Arandelas" },

  /* ---------- MOTORES ---------- */
  { categoria: "MOTORES", nombre: "Generadores eléctricos" },
  { categoria: "MOTORES", nombre: "Electrobombas" },
  { categoria: "MOTORES", nombre: "Hidroflow" },
  { categoria: "MOTORES", nombre: "Bombas sumergibles" },
  { categoria: "MOTORES", nombre: "Motobombas" },
  { categoria: "MOTORES", nombre: "Hidrolavadoras" },
  { categoria: "MOTORES", nombre: "Compresores" },
  { categoria: "MOTORES", nombre: "Motores" },

  /* ---------- PRODUCTOS ORNAMENTACIÓN ---------- */
  { categoria: "PRODUCTOS ORNAMENTACIÓN", nombre: "Equipo de soldar" },
  { categoria: "PRODUCTOS ORNAMENTACIÓN", nombre: "Carretas para soldar" },
  { categoria: "PRODUCTOS ORNAMENTACIÓN", nombre: "Tronzadoras" },
  { categoria: "PRODUCTOS ORNAMENTACIÓN", nombre: "Soldaduras" },
  { categoria: "PRODUCTOS ORNAMENTACIÓN", nombre: "Taladros" },
  { categoria: "PRODUCTOS ORNAMENTACIÓN", nombre: "Pulidoras" },
  { categoria: "PRODUCTOS ORNAMENTACIÓN", nombre: "Prensas" },
  { categoria: "PRODUCTOS ORNAMENTACIÓN", nombre: "Esmeriles" },

  /* ---------- PINTURA ---------- */
  { categoria: "PINTURA", nombre: "Esmalte" },
  { categoria: "PINTURA", nombre: "Vinilo" },
  { categoria: "PINTURA", nombre: "Pinturas para madera" },
  { categoria: "PINTURA", nombre: "Rodillos" },
  { categoria: "PINTURA", nombre: "Brochas" },
  { categoria: "PINTURA", nombre: "Pinceles" },

  /* ---------- SEGURIDAD INDUSTRIAL ---------- */
  { categoria: "SEGURIDAD INDUSTRIAL", nombre: "Gafas" },
  { categoria: "SEGURIDAD INDUSTRIAL", nombre: "Cascos" },
  { categoria: "SEGURIDAD INDUSTRIAL", nombre: "Botas de seguridad" },
  { categoria: "SEGURIDAD INDUSTRIAL", nombre: "Guantes" },
  { categoria: "SEGURIDAD INDUSTRIAL", nombre: "Protectores auditivos" },
  { categoria: "SEGURIDAD INDUSTRIAL", nombre: "Señalización" },
  { categoria: "SEGURIDAD INDUSTRIAL", nombre: "Camisas y pantalones" },

  /* ---------- PRODUCTOS DEL HOGAR ---------- */
  { categoria: "PRODUCTOS DEL HOGAR", nombre: "Estufa" },
  { categoria: "PRODUCTOS DEL HOGAR", nombre: "Ollas" },
  { categoria: "PRODUCTOS DEL HOGAR", nombre: "Sarténes" },
  { categoria: "PRODUCTOS DEL HOGAR", nombre: "Licuadora" },
  { categoria: "PRODUCTOS DEL HOGAR", nombre: "Molinos" },
  { categoria: "PRODUCTOS DEL HOGAR", nombre: "Vajillas" },
  { categoria: "PRODUCTOS DEL HOGAR", nombre: "Chocolateras" },
  { categoria: "PRODUCTOS DEL HOGAR", nombre: "Planchas" },
  { categoria: "PRODUCTOS DEL HOGAR", nombre: "Termos" },

  /* ---------- HIERRO ---------- */
  { categoria: "HIERRO", nombre: "Varillas" },
  { categoria: "HIERRO", nombre: "Ángulos" },
  { categoria: "HIERRO", nombre: "Platinas" },
  { categoria: "HIERRO", nombre: "Marco ventana" },
  { categoria: "HIERRO", nombre: "Marco puerta" },
  { categoria: "HIERRO", nombre: "Pasamanos" },
  { categoria: "HIERRO", nombre: "Tubería industrial" },
  { categoria: "HIERRO", nombre: "Tubería galvanizada" },
  { categoria: "HIERRO", nombre: "Lámina galvanizada" },
  { categoria: "HIERRO", nombre: "Lámina H2" },
  { categoria: "HIERRO", nombre: "Lámina alfajor" },
  { categoria: "HIERRO", nombre: "Lámina culrol" },
  { categoria: "HIERRO", nombre: "Canal U" },
  { categoria: "HIERRO", nombre: "Perfil en C" },

  /* ---------- HERRAMIENTAS ELÉCTRICAS ---------- */
  { categoria: "HERRAMIENTAS ELÉCTRICAS", nombre: "Lijadoras" },
  { categoria: "HERRAMIENTAS ELÉCTRICAS", nombre: "Rotomartillo" },
  { categoria: "HERRAMIENTAS ELÉCTRICAS", nombre: "Coladora" },
  { categoria: "HERRAMIENTAS ELÉCTRICAS", nombre: "Ruteadores" },
  { categoria: "HERRAMIENTAS ELÉCTRICAS", nombre: "Cepillos" },
  { categoria: "HERRAMIENTAS ELÉCTRICAS", nombre: "Demoledor" },
  { categoria: "HERRAMIENTAS ELÉCTRICAS", nombre: "Sopladoras" },
  { categoria: "HERRAMIENTAS ELÉCTRICAS", nombre: "Mototool" },
  { categoria: "HERRAMIENTAS ELÉCTRICAS", nombre: "Pistolas de calor" },

  /* ---------- TUBERÍA Y ACCESORIOS DE P.V.C ---------- */
  { categoria: "TUBERÍA Y ACCESORIOS DE P.V.C", nombre: "Tubería presión" },
  { categoria: "TUBERÍA Y ACCESORIOS DE P.V.C", nombre: "Tubería sanitaria" },
  { categoria: "TUBERÍA Y ACCESORIOS DE P.V.C", nombre: "Tubería novapor" },
  { categoria: "TUBERÍA Y ACCESORIOS DE P.V.C", nombre: "Tubería conduit" },
  { categoria: "TUBERÍA Y ACCESORIOS DE P.V.C", nombre: "Accesorios presión" },
  { categoria: "TUBERÍA Y ACCESORIOS DE P.V.C", nombre: "Accesorios sanitarios" },

  /* ---------- MATERIALES PARA CONSTRUCCIÓN ---------- */
  { categoria: "MATERIALES PARA CONSTRUCCIÓN", nombre: "Cemento" },
  { categoria: "MATERIALES PARA CONSTRUCCIÓN", nombre: "Cal" },
  { categoria: "MATERIALES PARA CONSTRUCCIÓN", nombre: "Bloque" },
  { categoria: "MATERIALES PARA CONSTRUCCIÓN", nombre: "Ladrillo tolete" },
  { categoria: "MATERIALES PARA CONSTRUCCIÓN", nombre: "Ladrillo rejilla" },
  { categoria: "MATERIALES PARA CONSTRUCCIÓN", nombre: "Impermeabilizantes" },
  { categoria: "MATERIALES PARA CONSTRUCCIÓN", nombre: "Siliconas" },
  { categoria: "MATERIALES PARA CONSTRUCCIÓN", nombre: "Canales cubiertas" },
  { categoria: "MATERIALES PARA CONSTRUCCIÓN", nombre: "Tejas" },
  { categoria: "MATERIALES PARA CONSTRUCCIÓN", nombre: "Malla electricidad" },
  { categoria: "MATERIALES PARA CONSTRUCCIÓN", nombre: "Eternit" },
  { categoria: "MATERIALES PARA CONSTRUCCIÓN", nombre: "Tabletas" },
  { categoria: "MATERIALES PARA CONSTRUCCIÓN", nombre: "Acelerantes" },
  { categoria: "MATERIALES PARA CONSTRUCCIÓN", nombre: "Cintas tapagoteras" },

  /* ---------- MANGUERAS ---------- */
  { categoria: "MANGUERAS", nombre: "Manguera negra" },
  { categoria: "MANGUERAS", nombre: "Manguera PF" },
  { categoria: "MANGUERAS", nombre: "Manguera peletizador" },
  { categoria: "MANGUERAS", nombre: "Manguera de cristal" },
  { categoria: "MANGUERAS", nombre: "Manguera de gas" },
  { categoria: "MANGUERAS", nombre: "Manguera alta presión" },
  { categoria: "MANGUERAS", nombre: "Manguera anillada" },
  { categoria: "MANGUERAS", nombre: "Manguera jardín" },
  { categoria: "MANGUERAS", nombre: "Manguera riegos" },

  /* ---------- TANQUES ---------- */
  { categoria: "TANQUES", nombre: "Tanques alto" },
  { categoria: "TANQUES", nombre: "Tanques bajo" },
  { categoria: "TANQUES", nombre: "Bebederos" },
  { categoria: "TANQUES", nombre: "Tanque cilíndrico" },
  { categoria: "TANQUES", nombre: "Comederos" },
  { categoria: "TANQUES", nombre: "Canecas plásticas" },

  /* ---------- HERRAMIENTAS MANUALES ---------- */
  { categoria: "HERRAMIENTAS MANUALES", nombre: "Llaves" },
  { categoria: "HERRAMIENTAS MANUALES", nombre: "Alicates" },
  { categoria: "HERRAMIENTAS MANUALES", nombre: "Flexómetros" },
  { categoria: "HERRAMIENTAS MANUALES", nombre: "Pinzas" },
  { categoria: "HERRAMIENTAS MANUALES", nombre: "Destornilladores" },
  { categoria: "HERRAMIENTAS MANUALES", nombre: "Tijeras" },
  { categoria: "HERRAMIENTAS MANUALES", nombre: "Bisturí" },
  { categoria: "HERRAMIENTAS MANUALES", nombre: "Tarrajas" },
  { categoria: "HERRAMIENTAS MANUALES", nombre: "Machuelos" },
  { categoria: "HERRAMIENTAS MANUALES", nombre: "Gato" },
  { categoria: "HERRAMIENTAS MANUALES", nombre: "Niveles" },
  { categoria: "HERRAMIENTAS MANUALES", nombre: "Grapadoras" },
  { categoria: "HERRAMIENTAS MANUALES", nombre: "Pistolas" },
  { categoria: "HERRAMIENTAS MANUALES", nombre: "Pistolas de impacto" },

  /* ---------- BAÑOS Y COCINAS ---------- */
  { categoria: "BAÑOS Y COCINAS", nombre: "Sanitario" },
  { categoria: "BAÑOS Y COCINAS", nombre: "Orinales" },
  { categoria: "BAÑOS Y COCINAS", nombre: "Lavamanos" },
  { categoria: "BAÑOS Y COCINAS", nombre: "Boquillas" },
  { categoria: "BAÑOS Y COCINAS", nombre: "Pegantes baldosas" },
  { categoria: "BAÑOS Y COCINAS", nombre: "Duchas" },
  { categoria: "BAÑOS Y COCINAS", nombre: "Registros" },
  { categoria: "BAÑOS Y COCINAS", nombre: "Accesorios baños" },
  { categoria: "BAÑOS Y COCINAS", nombre: "Lavaplatos" },

  /* ---------- QUÍMICOS ---------- */
  { categoria: "QUÍMICOS", nombre: "Soda cáustica" },
  { categoria: "QUÍMICOS", nombre: "Minerales" },
  { categoria: "QUÍMICOS", nombre: "Destapa cañerías" },
  { categoria: "QUÍMICOS", nombre: "Ácido muriático" },
  { categoria: "QUÍMICOS", nombre: "Disolvente pintura" },
  { categoria: "QUÍMICOS", nombre: "Productos piscinas" },

  /* ---------- PLÁSTICOS Y MALLAS ---------- */
  { categoria: "PLÁSTICOS Y MALLAS", nombre: "Plástico negro" },
  { categoria: "PLÁSTICOS Y MALLAS", nombre: "Plástico transparente" },
  { categoria: "PLÁSTICOS Y MALLAS", nombre: "Plástico" },
  { categoria: "PLÁSTICOS Y MALLAS", nombre: "Manel" },
  { categoria: "PLÁSTICOS Y MALLAS", nombre: "Angeos" },
  { categoria: "PLÁSTICOS Y MALLAS", nombre: "Telas" },
  { categoria: "PLÁSTICOS Y MALLAS", nombre: "Polisombras" },
  { categoria: "PLÁSTICOS Y MALLAS", nombre: "Geotextil" },
  { categoria: "PLÁSTICOS Y MALLAS", nombre: "Plásticos pizos" },
  { categoria: "PLÁSTICOS Y MALLAS", nombre: "Papel húmedo" },
  { categoria: "PLÁSTICOS Y MALLAS", nombre: "Thermopolin" },
  { categoria: "PLÁSTICOS Y MALLAS", nombre: "Malla zaranda" },
  { categoria: "PLÁSTICOS Y MALLAS", nombre: "Malla ganco" },
  { categoria: "PLÁSTICOS Y MALLAS", nombre: "Malla pajarito" },
  { categoria: "PLÁSTICOS Y MALLAS", nombre: "Malla plásticas" },
  { categoria: "PLÁSTICOS Y MALLAS", nombre: "Malla eslabonada" }
];
