const CATEGORIAS = [
  "AGRO",
  "ELÉCTRICO",
  "ABRASIVOS",
  "TORNILLERÍA",
  "MOTORES",
  "PRODUCTOS ORNAMENTACIÓN",
  "PINTURA",
  "SEGURIDAD INDUSTRIAL",
  "PRODUCTOS DEL HOGAR",
  "HIERRO",
  "HERRAMIENTAS ELÉCTRICAS",
  "TUBERÍA Y ACCESORIOS DE P.V.C",
  "MATERIALES PARA CONSTRUCCIÓN",
  "MANGUERAS",
  "TANQUES",
  "HERRAMIENTAS MANUALES",
  "BAÑOS Y COCINAS",
  "QUÍMICOS",
  "PLÁSTICOS Y MALLAS"
];

const PRODUCTOS = [
  /* agro */
  { categoria: "AGRO", nombre: "Cerca eléctrica", desc: "Energizador y alambre para cerca eléctrica.", img: "assets/img/CATEGORIAS/agro/cerca-electrica.webp" },
  { categoria: "AGRO", nombre: "Fumigadoras", desc: "Equipos para fumigar y controlar plagas.", img: "assets/img/CATEGORIAS/agro/fumigadoras.webp" },
  { categoria: "AGRO", nombre: "Herramientas", desc: "Herramientas para el trabajo del campo.", img: "assets/img/CATEGORIAS/agro/herramientas.webp" },
  { categoria: "AGRO", nombre: "Máquina agrícola", desc: "Motor estacionario para maquinaria agrícola.", img: "assets/img/CATEGORIAS/agro/motor-estacionario.webp" },
  { categoria: "AGRO", nombre: "Grapas y puntillas", desc: "Fijaciones para mallas y madera.", img: "assets/img/CATEGORIAS/agro/grapas-puntillas-y-alambre-de-pua.webp" },
  { categoria: "AGRO", nombre: "Alambre de púas", desc: "Alambre de púas para cerramientos.", img: "assets/img/CATEGORIAS/agro/grapas-puntillas-y-alambre-de-pua.webp" },
  { categoria: "AGRO", nombre: "Herraduras", desc: "Herraduras de calidad para equinos.", img: "assets/img/CATEGORIAS/agro/herraduras.webp" },

  /* eléctrico */
  { categoria: "ELÉCTRICO", nombre: "Cable", desc: "Cables eléctricos en varios calibres.", img: "assets/img/CATEGORIAS/electrico/cable-y-alambre.webp" },
  { categoria: "ELÉCTRICO", nombre: "Alambre", desc: "Alambre conductor para instalaciones.", img: "assets/img/CATEGORIAS/electrico/cable-y-alambre.webp" },
  { categoria: "ELÉCTRICO", nombre: "Lámparas", desc: "Luminarias para interior y exterior.", img: "assets/img/CATEGORIAS/electrico/lamparas-y-bombillas.webp" },
  { categoria: "ELÉCTRICO", nombre: "Bombillas", desc: "Iluminación LED y ahorradora.", img: "assets/img/CATEGORIAS/electrico/lamparas-y-bombillas.webp" },
  { categoria: "ELÉCTRICO", nombre: "Accesorios eléctricos", desc: "Tomacorrientes, interruptores y más.", img: "assets/img/CATEGORIAS/electrico/accesorios-electricos.webp" },
  { categoria: "ELÉCTRICO", nombre: "Medidor", desc: "Medidores de consumo eléctrico.", img: "assets/img/CATEGORIAS/electrico/medidor.webp" },
  { categoria: "ELÉCTRICO", nombre: "Cajas", desc: "Cajas de conexión y derivación.", img: "assets/img/CATEGORIAS/electrico/cajas.webp" },

  /* abrasivos */
  { categoria: "ABRASIVOS", nombre: "Lijas", desc: "Lijas de agua y grano para desbaste.", img: "assets/img/CATEGORIAS/abrasivos/abrasivos.webp" },
  { categoria: "ABRASIVOS", nombre: "Discos", desc: "Discos de corte y pulido.", img: "assets/img/CATEGORIAS/abrasivos/abrasivos.webp" },
  { categoria: "ABRASIVOS", nombre: "Grapas", desc: "Grapas de fijación.", img: "assets/img/CATEGORIAS/abrasivos/abrasivos.webp" },
  { categoria: "ABRASIVOS", nombre: "Limas", desc: "Limas para desbaste de hierro.", img: "assets/img/CATEGORIAS/abrasivos/abrasivos.webp" },
  { categoria: "ABRASIVOS", nombre: "Piedras", desc: "Piedras de afilar y desbaste.", img: "assets/img/CATEGORIAS/abrasivos/abrasivos.webp" },

  /* tornillería */
  { categoria: "TORNILLERÍA", nombre: "Drywall", desc: "Tornillos para instalación de drywall.", img: "assets/img/CATEGORIAS/tornilleria/tornilleria.webp" },
  { categoria: "TORNILLERÍA", nombre: "Tornillos para estufa", desc: "Tornillos y patas para estufas.", img: "assets/img/CATEGORIAS/tornilleria/tornillos_2.webp" },
  { categoria: "TORNILLERÍA", nombre: "Carriage", desc: "Tornillos tipo carriage.", img: "assets/img/CATEGORIAS/tornilleria/torinillos_1.webp" },
  { categoria: "TORNILLERÍA", nombre: "Tuercas", desc: "Tuercas de distintas medidas.", img: "assets/img/CATEGORIAS/tornilleria/tornillos_2.webp" },
  { categoria: "TORNILLERÍA", nombre: "ROG", desc: "Tornillos roscados de fijación.", img: "assets/img/CATEGORIAS/tornilleria/torinillos_1.webp" },
  { categoria: "TORNILLERÍA", nombre: "Lámina", desc: "Tornillos para lámina y cubierta.", img: "assets/img/CATEGORIAS/tornilleria/tornillos_2.webp" },
  { categoria: "TORNILLERÍA", nombre: "Autoperforante", desc: "Tornillos que perforan y fijan.", img: "assets/img/CATEGORIAS/tornilleria/tornilleria.webp" },
  { categoria: "TORNILLERÍA", nombre: "Cabeza lenteja", desc: "Tornillos de cabeza plana ancha.", img: "assets/img/CATEGORIAS/tornilleria/tornilleria.webp" },
  { categoria: "TORNILLERÍA", nombre: "Grado 6", desc: "Pernos de alta resistencia grado 6.", img: "assets/img/CATEGORIAS/tornilleria/torinillos_1.webp" },
  { categoria: "TORNILLERÍA", nombre: "Arandelas", desc: "Arandelas de varios diámetros.", img: "assets/img/CATEGORIAS/tornilleria/tornillos_2.webp" },
  { categoria: "TORNILLERÍA", nombre: "Remaches", desc: "Remaches de fijación para lámina.", img: "assets/img/CATEGORIAS/tornilleria/remaches.webp" },
  { categoria: "TORNILLERÍA", nombre: "Abrazaderas", desc: "Abrazaderas de sujeción.", img: "assets/img/CATEGORIAS/tornilleria/remaches.webp" },

  /* motores */
  { categoria: "MOTORES", nombre: "Generador eléctrico", desc: "Energía de respaldo para obra y casa.", img: "assets/img/CATEGORIAS/motores/generadores-electricos.webp" },
  { categoria: "MOTORES", nombre: "Electrobombas", desc: "Bombas eléctricas para agua.", img: "assets/img/CATEGORIAS/motores/electro-bombas.webp" },
  { categoria: "MOTORES", nombre: "Hidroflow", desc: "Descarga y accesorios de presión.", img: "assets/img/CATEGORIAS/motores/hidroflow.webp" },
  { categoria: "MOTORES", nombre: "Bomba sumergible", desc: "Bomba para pozos y tanques." },
  { categoria: "MOTORES", nombre: "Motobombas", desc: "Motobombas portátiles para riego.", img: "assets/img/CATEGORIAS/motores/moto-bombas.webp" },
  { categoria: "MOTORES", nombre: "Hidrolavadoras", desc: "Limpieza de equipos a alta presión.", img: "assets/img/CATEGORIAS/motores/hidrolavadoras.webp" },
  { categoria: "MOTORES", nombre: "Compresores", desc: "Aire comprimido para taller y obra.", img: "assets/img/CATEGORIAS/motores/compresores.webp" },

  /* ornamentación */
  { categoria: "PRODUCTOS ORNAMENTACIÓN", nombre: "Equipo de soldar", desc: "Plantas y equipos de soldadura.", img: "assets/img/CATEGORIAS/productos-de-ornamentacion/equipo-de-soldar.webp" },
  { categoria: "PRODUCTOS ORNAMENTACIÓN", nombre: "Caretas para soldar", desc: "Caretas de protección para soldadura.", img: "assets/img/CATEGORIAS/productos-de-ornamentacion/caretas-soldadura.webp" },
  { categoria: "PRODUCTOS ORNAMENTACIÓN", nombre: "Tronzadoras", desc: "Tronzadora para corte de metal.", img: "assets/img/CATEGORIAS/productos-de-ornamentacion/tronzadoras.webp" },
  { categoria: "PRODUCTOS ORNAMENTACIÓN", nombre: "Soldaduras", desc: "Varillas y electrodos para soldar.", img: "assets/img/CATEGORIAS/productos-de-ornamentacion/soldadura.webp" },
  { categoria: "PRODUCTOS ORNAMENTACIÓN", nombre: "Taladros", desc: "Taladros de batería y cable.", img: "assets/img/CATEGORIAS/productos-de-ornamentacion/taladros.webp" },
  { categoria: "PRODUCTOS ORNAMENTACIÓN", nombre: "Taladro de árbol", desc: "Taladro de árbol para perforación precisa.", img: "assets/img/CATEGORIAS/productos-de-ornamentacion/taladro-de-armol.webp" },
  { categoria: "PRODUCTOS ORNAMENTACIÓN", nombre: "Pulidoras", desc: "Pulidoras de acabado.", img: "assets/img/CATEGORIAS/productos-de-ornamentacion/pulidoras.webp" },
  { categoria: "PRODUCTOS ORNAMENTACIÓN", nombre: "Prensas", desc: "Prensas de banco y de mano.", img: "assets/img/CATEGORIAS/productos-de-ornamentacion/prensas.webp" },
  { categoria: "PRODUCTOS ORNAMENTACIÓN", nombre: "Esmeriles", desc: "Esmeriles para desbaste de metal.", img: "assets/img/CATEGORIAS/productos-de-ornamentacion/esmeriles.webp" },

  /* pintura */
  { categoria: "PINTURA", nombre: "Esmalte Every", desc: "Esmalte sintético en varios colores.", img: "assets/img/CATEGORIAS/pinturas/every.webp" },
  { categoria: "PINTURA", nombre: "Esmalte Pintuco", desc: "Esmalte sintético de alta duración.", img: "assets/img/CATEGORIAS/pinturas/pintuco.webp" },
  { categoria: "PINTURA", nombre: "Esmalte Pintuland", desc: "Esmalte para acabados interiores y exteriores.", img: "assets/img/CATEGORIAS/pinturas/pintuland.webp" },
  { categoria: "PINTURA", nombre: "Vinilo Every", desc: "Pintura vinilo lavable.", img: "assets/img/CATEGORIAS/pinturas/every.webp" },
  { categoria: "PINTURA", nombre: "Vinilo Pintuco", desc: "Pintura vinilo para muros.", img: "assets/img/CATEGORIAS/pinturas/pintuco.webp" },
  { categoria: "PINTURA", nombre: "Vinilo Pintuland", desc: "Pintura vinilo de cobertura.", img: "assets/img/CATEGORIAS/pinturas/pintuland.webp" },
  { categoria: "PINTURA", nombre: "Rodillos", desc: "Rodillos y esponjas para pintar.", img: "assets/img/CATEGORIAS/pinturas/rodillos-brochas-y-pinceles.webp" },
  { categoria: "PINTURA", nombre: "Brochas", desc: "Brochas de varios anchos.", img: "assets/img/CATEGORIAS/pinturas/rodillos-brochas-y-pinceles.webp" },
  { categoria: "PINTURA", nombre: "Pinceles", desc: "Pinceles para detalles y filo.", img: "assets/img/CATEGORIAS/pinturas/rodillos-brochas-y-pinceles.webp" },

  /* seguridad industrial */
  { categoria: "SEGURIDAD INDUSTRIAL", nombre: "Gafas", desc: "Gafas de protección para los ojos.", img: "assets/img/CATEGORIAS/seguridad-industrial/seguridad-2.webp" },
  { categoria: "SEGURIDAD INDUSTRIAL", nombre: "Cascos", desc: "Cascos de protección laboral.", img: "assets/img/CATEGORIAS/seguridad-industrial/seguridad-2.webp" },
  { categoria: "SEGURIDAD INDUSTRIAL", nombre: "Botas de seguridad", desc: "Botas con puntera de acero.", img: "assets/img/CATEGORIAS/seguridad-industrial/seguridad-2.webp" },
  { categoria: "SEGURIDAD INDUSTRIAL", nombre: "Guantes", desc: "Guantes de trabajo y manejo.", img: "assets/img/CATEGORIAS/seguridad-industrial/seguridad-1.webp" },
  { categoria: "SEGURIDAD INDUSTRIAL", nombre: "Protectores auditivos", desc: "Protectores auditivos para trabajo en zonas ruidosas.", img: "assets/img/CATEGORIAS/seguridad-industrial/seguridad-2.webp" },
  { categoria: "SEGURIDAD INDUSTRIAL", nombre: "Señalización", desc: "Cintas, extintores y señales.", img: "assets/img/CATEGORIAS/seguridad-industrial/seguridad-1.webp" },
  { categoria: "SEGURIDAD INDUSTRIAL", nombre: "Camisas y pantalones", desc: "Dotación de trabajo.", img: "assets/img/CATEGORIAS/seguridad-industrial/seguridad-2.webp" },

  /* hogar */
  { categoria: "PRODUCTOS DEL HOGAR", nombre: "Estufa de mesa", desc: "Estufa de mesa para gas propano.", img: "assets/img/CATEGORIAS/productos-del-hogar/estufa-de-mesa.webp" },
  { categoria: "PRODUCTOS DEL HOGAR", nombre: "Estufa de leña", desc: "Estufa de leña para el hogar.", img: "assets/img/CATEGORIAS/productos-del-hogar/estufa-de-lena.webp" },
  { categoria: "PRODUCTOS DEL HOGAR", nombre: "Estufa industrial", desc: "Estufa industrial de alto rendimiento.", img: "assets/img/CATEGORIAS/productos-del-hogar/estufa-industrial.webp" },
  { categoria: "PRODUCTOS DEL HOGAR", nombre: "Ollas", desc: "Ollas de cocina y accesorios.", img: "assets/img/CATEGORIAS/productos-del-hogar/productos-1.webp" },
  { categoria: "PRODUCTOS DEL HOGAR", nombre: "Sartenes", desc: "Juegos de sartenes antiadherentes.", img: "assets/img/CATEGORIAS/productos-del-hogar/productos-1.webp" },
  { categoria: "PRODUCTOS DEL HOGAR", nombre: "Licuadora", desc: "Licuadoras de uso casero.", img: "assets/img/CATEGORIAS/productos-del-hogar/productos-1.webp" },
  { categoria: "PRODUCTOS DEL HOGAR", nombre: "Molinos", desc: "Molinos eléctricos para granos y carne.", img: "assets/img/CATEGORIAS/productos-del-hogar/molino-granos-y-carne-electricos.webp" },
  { categoria: "PRODUCTOS DEL HOGAR", nombre: "Vajillas", desc: "Vajillas completas para el hogar.", img: "assets/img/CATEGORIAS/productos-del-hogar/productos-1.webp" },
  { categoria: "PRODUCTOS DEL HOGAR", nombre: "Chocolateras", desc: "Chocolateras para la cocina.", img: "assets/img/CATEGORIAS/productos-del-hogar/productos-1.webp" },
  { categoria: "PRODUCTOS DEL HOGAR", nombre: "Planchas", desc: "Planchas de ropa y de cocina.", img: "assets/img/CATEGORIAS/productos-del-hogar/productos-1.webp" },
  { categoria: "PRODUCTOS DEL HOGAR", nombre: "Termos", desc: "Termos de doble pared.", img: "assets/img/CATEGORIAS/productos-del-hogar/termos.webp" },

  /* hierro */
  { categoria: "HIERRO", nombre: "Varillas", desc: "Varillas corrugadas para construcción.", img: "assets/img/CATEGORIAS/hierro/varillas.webp" },
  { categoria: "HIERRO", nombre: "Ángulos", desc: "Ángulos de acero y hierro.", img: "assets/img/CATEGORIAS/hierro/angulos.webp" },
  { categoria: "HIERRO", nombre: "Platinas", desc: "Platinas planas de acero.", img: "assets/img/CATEGORIAS/hierro/platinas.webp" },
  { categoria: "HIERRO", nombre: "Marco ventana", desc: "Marcos para ventanas de vidrio.", img: "assets/img/CATEGORIAS/hierro/marco-ventana.webp" },
  { categoria: "HIERRO", nombre: "Marco puerta", desc: "Marcos para puertas.", img: "assets/img/CATEGORIAS/hierro/marco-puerta.webp" },
  { categoria: "HIERRO", nombre: "Pasamanos", desc: "Pasamanos para escaleras.", img: "assets/img/CATEGORIAS/hierro/pasamanos.webp" },
  { categoria: "HIERRO", nombre: "Tubería industrial", desc: "Tubería de hierro pesado.", img: "assets/img/CATEGORIAS/hierro/tuberia-industrial.webp", fondo: "foto" },
  { categoria: "HIERRO", nombre: "Tubería galvanizada", desc: "Tubería galvanizada para desagües.", img: "assets/img/CATEGORIAS/hierro/tuberia-galvanizada.webp" },
  { categoria: "HIERRO", nombre: "Lámina galvanizada", desc: "Láminas galvanizadas para cubierta.", img: "assets/img/CATEGORIAS/hierro/lamina-galvanizada.webp", fondo: "foto" },
  { categoria: "HIERRO", nombre: "Lámina HR", desc: "Láminas HR de acero laminado en caliente.", img: "assets/img/CATEGORIAS/hierro/lamina-hr.webp" },
  { categoria: "HIERRO", nombre: "Lámina alfajor", desc: "Láminas tipo alfajor.", img: "assets/img/CATEGORIAS/hierro/lamina-alfajor.webp" },
  { categoria: "HIERRO", nombre: "Lámina Col Rol", desc: "Láminas Col Rol de acero laminado en frío.", img: "assets/img/CATEGORIAS/hierro/lamina-colrol.webp" },
  { categoria: "HIERRO", nombre: "Canal U", desc: "Canales y accesorios estructurales.", img: "assets/img/CATEGORIAS/hierro/canal-u.webp" },
  { categoria: "HIERRO", nombre: "Perfil en C", desc: "Perfiles estructurales tipo C.", img: "assets/img/CATEGORIAS/hierro/perfil-en-c.webp" },

  /* herramientas eléctricas */
  { categoria: "HERRAMIENTAS ELÉCTRICAS", nombre: "Lijadoras", desc: "Lijadoras eléctricas para acabado.", img: "assets/img/CATEGORIAS/herramientas-electricas/lijadoras.webp" },
  { categoria: "HERRAMIENTAS ELÉCTRICAS", nombre: "Rotomartillo", desc: "Rotomartillos para perforar muros.", img: "assets/img/CATEGORIAS/herramientas-electricas/rotomartillo.webp" },
  { categoria: "HERRAMIENTAS ELÉCTRICAS", nombre: "Caladora", desc: "Caladora para cortes curvos y acabado.", img: "assets/img/CATEGORIAS/herramientas-electricas/caladoras.webp" },
  { categoria: "HERRAMIENTAS ELÉCTRICAS", nombre: "Ruteadores", desc: "Ruteadores para perfilado de madera.", img: "assets/img/CATEGORIAS/herramientas-electricas/ruteadora.webp" },
  { categoria: "HERRAMIENTAS ELÉCTRICAS", nombre: "Cepillos", desc: "Cepillos eléctricos para madera.", img: "assets/img/CATEGORIAS/herramientas-electricas/cepillos-electricos-madera.webp" },
  { categoria: "HERRAMIENTAS ELÉCTRICAS", nombre: "Demoledor", desc: "Demoledores de muros y concreto.", img: "assets/img/CATEGORIAS/herramientas-electricas/demoledor.webp" },
  { categoria: "HERRAMIENTAS ELÉCTRICAS", nombre: "Sopladoras", desc: "Sopladoras para limpieza y obra.", img: "assets/img/CATEGORIAS/herramientas-electricas/sopladora.webp" },
  { categoria: "HERRAMIENTAS ELÉCTRICAS", nombre: "Motortool", desc: "Motortool de uso múltiple.", img: "assets/img/CATEGORIAS/herramientas-electricas/motortool.webp" },
  { categoria: "HERRAMIENTAS ELÉCTRICAS", nombre: "Pistolas de calor", desc: "Pistolas de aire caliente.", img: "assets/img/CATEGORIAS/herramientas-electricas/pistola-de-calor.webp" },

  /* tubería pvc */
  { categoria: "TUBERÍA Y ACCESORIOS DE P.V.C", nombre: "Tubería presión", desc: "Tubería P.V.C de presión.", img: "assets/img/CATEGORIAS/tuberia-y-accesorios-pvc/tuberia-presion.webp" },
  { categoria: "TUBERÍA Y ACCESORIOS DE P.V.C", nombre: "Tubería sanitaria", desc: "Tubería sanitaria para desagües.", img: "assets/img/CATEGORIAS/tuberia-y-accesorios-pvc/tuberia-sanitaria.webp", fondo: "foto" },
  { categoria: "TUBERÍA Y ACCESORIOS DE P.V.C", nombre: "Tubería Novafor", desc: "Tubería Novafor y accesorios.", img: "assets/img/CATEGORIAS/tuberia-y-accesorios-pvc/tuberia-novafor.webp" },
  { categoria: "TUBERÍA Y ACCESORIOS DE P.V.C", nombre: "Tubería conduit", desc: "Tubería conduit para cables.", img: "assets/img/CATEGORIAS/tuberia-y-accesorios-pvc/tuberia-conduit.webp" },
  { categoria: "TUBERÍA Y ACCESORIOS DE P.V.C", nombre: "Accesorios presión", desc: "Codos y uniones de presión.", img: "assets/img/CATEGORIAS/tuberia-y-accesorios-pvc/accesorio-presion.webp" },
  { categoria: "TUBERÍA Y ACCESORIOS DE P.V.C", nombre: "Accesorios sanitarios", desc: "Registros y descargas sanitarias.", img: "assets/img/CATEGORIAS/tuberia-y-accesorios-pvc/accesorios-sanitarios.webp" },

  /* materiales de construcción */
  { categoria: "MATERIALES PARA CONSTRUCCIÓN", nombre: "Cemento", desc: "Cemento gris para obra.", img: "assets/img/CATEGORIAS/materiales-de-construccion/cemento.webp" },
  { categoria: "MATERIALES PARA CONSTRUCCIÓN", nombre: "Cal", desc: "Cales de construcción.", img: "assets/img/CATEGORIAS/materiales-de-construccion/cal-hidratada.webp" },
  { categoria: "MATERIALES PARA CONSTRUCCIÓN", nombre: "Bloque", desc: "Bloques de arcilla y cemento.", img: "assets/img/CATEGORIAS/materiales-de-construccion/bloques.webp" },
  { categoria: "MATERIALES PARA CONSTRUCCIÓN", nombre: "Ladrillo tolete", desc: "Ladrillo tolete para mampostería.", img: "assets/img/CATEGORIAS/materiales-de-construccion/ladrillos-y-ladrillo-rejilla.webp" },
  { categoria: "MATERIALES PARA CONSTRUCCIÓN", nombre: "Ladrillo rejilla", desc: "Ladrillo rejilla ventilado.", img: "assets/img/CATEGORIAS/materiales-de-construccion/ladrillos-y-ladrillo-rejilla.webp" },
  { categoria: "MATERIALES PARA CONSTRUCCIÓN", nombre: "Impermeabilizantes", desc: "Impermeabilizante para muros y techos.", img: "assets/img/CATEGORIAS/materiales-de-construccion/impermeabilizantes-y-acelerantes.webp" },
  { categoria: "MATERIALES PARA CONSTRUCCIÓN", nombre: "Siliconas", desc: "Silicona y selladores.", img: "assets/img/CATEGORIAS/materiales-de-construccion/siliconas.webp" },
  { categoria: "MATERIALES PARA CONSTRUCCIÓN", nombre: "Canales cubiertas", desc: "Canales para cubiertas y lluvia.", img: "assets/img/CATEGORIAS/materiales-de-construccion/canales.webp" },
  { categoria: "MATERIALES PARA CONSTRUCCIÓN", nombre: "Tejas", desc: "Tejas de zinc para cubierta.", img: "assets/img/CATEGORIAS/materiales-de-construccion/tejas-zinc.webp" },
  { categoria: "MATERIALES PARA CONSTRUCCIÓN", nombre: "Malla electrosoldada", desc: "Malla electrosoldada de refuerzo.", img: "assets/img/CATEGORIAS/materiales-de-construccion/malla-electrosoldada.webp" },
  { categoria: "MATERIALES PARA CONSTRUCCIÓN", nombre: "Eternit", desc: "Tejas Eternit y fibrocemento.", img: "assets/img/CATEGORIAS/materiales-de-construccion/eternit.webp" },
  { categoria: "MATERIALES PARA CONSTRUCCIÓN", nombre: "Tabletas", desc: "Tabletas de piso y fachada.", img: "assets/img/CATEGORIAS/materiales-de-construccion/tableta.webp" },
  { categoria: "MATERIALES PARA CONSTRUCCIÓN", nombre: "Acelerantes", desc: "Acelerante de fraguado.", img: "assets/img/CATEGORIAS/materiales-de-construccion/impermeabilizantes-y-acelerantes.webp" },
  { categoria: "MATERIALES PARA CONSTRUCCIÓN", nombre: "Cintas tapagoteras", desc: "Cintas tapagoteras para cubierta.", img: "assets/img/CATEGORIAS/materiales-de-construccion/cintas-tapa-gotera.webp" },

  /* mangueras */
  { categoria: "MANGUERAS", nombre: "Manguera negra", desc: "Manguera negra de conducción.", img: "assets/img/CATEGORIAS/mangueras/manguera-negra.webp" },
  { categoria: "MANGUERAS", nombre: "Manguera PF", desc: "Manguera P.F. reforzada.", img: "assets/img/CATEGORIAS/mangueras/manguera-pf.webp" },
  { categoria: "MANGUERAS", nombre: "Manguera peletizada", desc: "Manguera peletizada para riego.", img: "assets/img/CATEGORIAS/mangueras/manguera-peletizada.webp" },
  { categoria: "MANGUERAS", nombre: "Manguera de cristal", desc: "Manguera transparente de cristal.", img: "assets/img/CATEGORIAS/mangueras/manguera-cristal.webp" },
  { categoria: "MANGUERAS", nombre: "Manguera de gas", desc: "Manguera para gas certificada.", img: "assets/img/CATEGORIAS/mangueras/manguera-gas.webp" },
  { categoria: "MANGUERAS", nombre: "Manguera alta presión", desc: "Manguera de alta presión." },
  { categoria: "MANGUERAS", nombre: "Manguera anillada", desc: "Manguera anillada reforzada." },
  { categoria: "MANGUERAS", nombre: "Manguera jardín", desc: "Manguera de jardín." },
  { categoria: "MANGUERAS", nombre: "Manguera riegos", desc: "Manguera de riego agrícola." },

  /* tanques */
  { categoria: "TANQUES", nombre: "Tanques alto", desc: "Tanques altos para agua.", img: "assets/img/CATEGORIAS/tanques/tanque-alto.webp" },
  { categoria: "TANQUES", nombre: "Tanques bajo", desc: "Tanques bajos para agua.", img: "assets/img/CATEGORIAS/tanques/tanque-bajo.webp" },
  { categoria: "TANQUES", nombre: "Bebederos", desc: "Bebederos para ganado.", img: "assets/img/CATEGORIAS/tanques/bebedero.webp" },
  { categoria: "TANQUES", nombre: "Tanque cilíndrico", desc: "Tanque cilíndrico vertical.", img: "assets/img/CATEGORIAS/tanques/tanque-cilindrico.webp" },
  { categoria: "TANQUES", nombre: "Comederos", desc: "Comederos para ganado.", img: "assets/img/CATEGORIAS/tanques/comederos.webp" },
  { categoria: "TANQUES", nombre: "Canecas plásticas", desc: "Canecas y recipientes plásticos.", img: "assets/img/CATEGORIAS/tanques/canecas-plasticas.webp" },

  /* herramientas manuales */
  { categoria: "HERRAMIENTAS MANUALES", nombre: "Llaves", desc: "Llaves de ajuste y boca.", img: "assets/img/CATEGORIAS/herramientas-manuales/llaves-y-pinzas.webp" },
  { categoria: "HERRAMIENTAS MANUALES", nombre: "Alicates", desc: "Alicates de corte y uso.", img: "assets/img/CATEGORIAS/herramientas-manuales/alicates.webp" },
  { categoria: "HERRAMIENTAS MANUALES", nombre: "Flexómetros", desc: "Flexómetros y cintas métricas.", img: "assets/img/CATEGORIAS/herramientas-manuales/flexometros.webp" },
  { categoria: "HERRAMIENTAS MANUALES", nombre: "Pinzas", desc: "Pinzas de precisión.", img: "assets/img/CATEGORIAS/herramientas-manuales/llaves-y-pinzas.webp" },
  { categoria: "HERRAMIENTAS MANUALES", nombre: "Destornilladores", desc: "Destornilladores de varios tipos.", img: "assets/img/CATEGORIAS/herramientas-manuales/destornilladoress.webp" },
  { categoria: "HERRAMIENTAS MANUALES", nombre: "Tijeras", desc: "Tijeras de todo uso." },
  { categoria: "HERRAMIENTAS MANUALES", nombre: "Bisturí", desc: "Bisturí de precisión.", img: "assets/img/CATEGORIAS/herramientas-manuales/bisturi.webp" },
  { categoria: "HERRAMIENTAS MANUALES", nombre: "Tarrajas", desc: "Tarrajas para roscar tubería.", img: "assets/img/CATEGORIAS/herramientas-manuales/machuelos-y-tarrajas.webp" },
  { categoria: "HERRAMIENTAS MANUALES", nombre: "Machuelos", desc: "Machuelos para roscado.", img: "assets/img/CATEGORIAS/herramientas-manuales/machuelos-y-tarrajas.webp" },
  { categoria: "HERRAMIENTAS MANUALES", nombre: "Gato", desc: "Gato de levantamiento.", img: "assets/img/CATEGORIAS/herramientas-manuales/gatos.webp" },
  { categoria: "HERRAMIENTAS MANUALES", nombre: "Niveles", desc: "Niveles de burbuja.", img: "assets/img/CATEGORIAS/herramientas-manuales/niveles.webp" },
  { categoria: "HERRAMIENTAS MANUALES", nombre: "Grapadoras", desc: "Grapadoras de fijación.", img: "assets/img/CATEGORIAS/herramientas-manuales/grapadoras.webp" },
  { categoria: "HERRAMIENTAS MANUALES", nombre: "Pistolas de impacto", desc: "Pistola de impacto neumática.", img: "assets/img/CATEGORIAS/herramientas-manuales/pistola-de-impacto.webp" },

  /* baños y cocinas */
  { categoria: "BAÑOS Y COCINAS", nombre: "Sanitario", desc: "Sanitario de porcelana.", img: "assets/img/CATEGORIAS/banos-y-cocinas/sanitarios-y-lavamanos.webp" },
  { categoria: "BAÑOS Y COCINAS", nombre: "Orinales", desc: "Orinales para baño.", img: "assets/img/CATEGORIAS/banos-y-cocinas/sanitarios-y-lavamanos.webp" },
  { categoria: "BAÑOS Y COCINAS", nombre: "Lavamanos", desc: "Lavamanos de baño.", img: "assets/img/CATEGORIAS/banos-y-cocinas/sanitarios-y-lavamanos.webp" },
  { categoria: "BAÑOS Y COCINAS", nombre: "Boquillas", desc: "Boquillas y accesorios.", img: "assets/img/CATEGORIAS/banos-y-cocinas/boquilla.webp" },
  { categoria: "BAÑOS Y COCINAS", nombre: "Pegantes baldosas", desc: "Pegante para baldosas." },
  { categoria: "BAÑOS Y COCINAS", nombre: "Duchas", desc: "Duchas y regaderas." },
  { categoria: "BAÑOS Y COCINAS", nombre: "Registros", desc: "Registros de agua y accesorios." },
  { categoria: "BAÑOS Y COCINAS", nombre: "Accesorios baños", desc: "Accesorios de baño y cocina." },
  { categoria: "BAÑOS Y COCINAS", nombre: "Lavaplatos", desc: "Lavaplatos para cocina.", img: "assets/img/CATEGORIAS/banos-y-cocinas/lavaplatos.webp" },

  /* químicos */
  { categoria: "QUÍMICOS", nombre: "Soda cáustica", desc: "Soda cáustica de limpieza." },
  { categoria: "QUÍMICOS", nombre: "Minerales", desc: "Minerales de uso doméstico.", img: "assets/img/CATEGORIAS/materiales-de-construccion/minerales.webp" },
  { categoria: "QUÍMICOS", nombre: "Destapa cañerías", desc: "Destapador de cañerías.", img: "assets/img/CATEGORIAS/quimicos/destapacanerias.webp" },
  { categoria: "QUÍMICOS", nombre: "Ácido muriático", desc: "Ácido muriático de limpieza.", img: "assets/img/CATEGORIAS/quimicos/acido-muriatico.webp" },
  { categoria: "QUÍMICOS", nombre: "Disolvente pintura", desc: "Disolvente para pintura." },
  { categoria: "QUÍMICOS", nombre: "Productos piscinas", desc: "Químicos para piscinas.", img: "assets/img/CATEGORIAS/quimicos/producto-piscina.webp" },

  /* plásticos y mallas */
  { categoria: "PLÁSTICOS Y MALLAS", nombre: "Plástico negro", desc: "Plástico negro para obra.", img: "assets/img/CATEGORIAS/plasticos-y-mallas/plasticos.webp" },
  { categoria: "PLÁSTICOS Y MALLAS", nombre: "Plástico transparente", desc: "Plástico transparente de uso.", img: "assets/img/CATEGORIAS/plasticos-y-mallas/plasticos.webp" },
  { categoria: "PLÁSTICOS Y MALLAS", nombre: "Plástico", desc: "Plástico de uso general.", img: "assets/img/CATEGORIAS/plasticos-y-mallas/plasticos.webp" },
  { categoria: "PLÁSTICOS Y MALLAS", nombre: "Mantel", desc: "Mantel y accesorios plásticos.", img: "assets/img/CATEGORIAS/plasticos-y-mallas/manteles.webp" },
  { categoria: "PLÁSTICOS Y MALLAS", nombre: "Anjeos", desc: "Anjeos de yute para cerramiento.", img: "assets/img/CATEGORIAS/plasticos-y-mallas/plasticos.webp" },
  { categoria: "PLÁSTICOS Y MALLAS", nombre: "Telas", desc: "Telas plásticas y sombra.", img: "assets/img/CATEGORIAS/plasticos-y-mallas/manteles.webp" },
  { categoria: "PLÁSTICOS Y MALLAS", nombre: "Polisombras", desc: "Polisombra para cultivos.", img: "assets/img/CATEGORIAS/plasticos-y-mallas/plasticos.webp" },
  { categoria: "PLÁSTICOS Y MALLAS", nombre: "Geotextil", desc: "Geotextil de refuerzo.", img: "assets/img/CATEGORIAS/plasticos-y-mallas/plasticos.webp" },
  { categoria: "PLÁSTICOS Y MALLAS", nombre: "Plásticos pisos", desc: "Plástico para pisos.", img: "assets/img/CATEGORIAS/plasticos-y-mallas/plasticos.webp" },
  { categoria: "PLÁSTICOS Y MALLAS", nombre: "Papel húmedo", desc: "Papel húmedo industrial.", img: "assets/img/CATEGORIAS/plasticos-y-mallas/plasticos.webp" },
  { categoria: "PLÁSTICOS Y MALLAS", nombre: "Thermopolin", desc: "Thermopolin de protección.", img: "assets/img/CATEGORIAS/plasticos-y-mallas/plasticos.webp" },
  { categoria: "PLÁSTICOS Y MALLAS", nombre: "Malla zaranda", desc: "Malla zaranda de hierro.", img: "assets/img/CATEGORIAS/plasticos-y-mallas/plasticos.webp" },
  { categoria: "PLÁSTICOS Y MALLAS", nombre: "Malla ganco", desc: "Malla de protección.", img: "assets/img/CATEGORIAS/plasticos-y-mallas/plasticos.webp" },
  { categoria: "PLÁSTICOS Y MALLAS", nombre: "Malla pajarito", desc: "Malla anti-pájaros.", img: "assets/img/CATEGORIAS/plasticos-y-mallas/plasticos.webp" },
  { categoria: "PLÁSTICOS Y MALLAS", nombre: "Malla plásticas", desc: "Malla de plástico.", img: "assets/img/CATEGORIAS/plasticos-y-mallas/plasticos.webp" },
  { categoria: "PLÁSTICOS Y MALLAS", nombre: "Malla eslabonada", desc: "Malla eslabonada de cerramiento.", img: "assets/img/CATEGORIAS/plasticos-y-mallas/plasticos.webp" }
];
